language: node_js
node_js:
  - "node"
  - "8"
  - "7"
  - "9"
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - npm test
  - npm run coveralls
sudo: required
services:
  - docker
deploy:
  provider: script
  script: bash docker_push
